import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { Providers } from '../providers/Providers'
import { theme } from '@/assets/style'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-br'>
      <body
        style={{
          padding: theme.space.defaultPadding,
          background: theme.color.neutral
        }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
